services:
 backend:
  build:
   context: ./backend
   dockerfile: Dockerfile
  container_name: mentor_app
  volumes:
   - ./backend:/var/www/html
  # ports:
  #  - '9000:9000'
  networks:
   - app-network
  depends_on:
   - mentor_db

 frontend:
  build:
   context: ./frontend
   dockerfile: Dockerfile
  container_name: mentor_nextjs_app
  ports:
   - '3000:3000'
  volumes:
   - ./frontend:/app:rw
   - /app/node_modules
   - ./.env:/app/.env
  environment:
   - NODE_ENV=${NODE_ENV:-production}
  networks:
   - app-network

 nginx:
  image: nginx:latest
  container_name: mentor_nginx
  restart: unless-stopped
  ports:
   - '80:80'
  volumes:
   - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
   - ./frontend:/app 
   - ./backend:/var/www/html
  depends_on:
   - backend
   - frontend
  networks:
   - app-network

 mentor_db:
  platform: linux/amd64
  image: mysql
  restart: unless-stopped
  tty: true
  container_name: mentor_db
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: laravel
   MYSQL_USER: laravel
   MYSQL_PASSWORD: laravel
  ports:
   - '3306:3306'
  volumes:
   - ./docker/mysql:/var/lib/mysql
  networks:
   - app-network

networks:
 app-network:
  driver: bridge

volumes:
 dbdata:
